name: Formatting And Linting
on: pull_request
jobs:
  formatting-and-linting:
    name: Formatting And Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
      - name: Install Packages
        run: pip install poetry && poetry install
      - name: Run Black
        uses: psf/black@stable
      - name: Run Flake8
        uses: py-actions/flake8@v2
      - name: Run Pylint
        run: pylint src/
      - name: Run Ruff
        uses: chartboost/ruff-action@v1
